import { test, expect } from '@playwright/test';

test('crear cliente', async ({ page }) => {
  await page.goto('http://127.0.0.1:8000/admin');
  await page.getByRole('link', { name: 'Clientes' }).click();
  await page.getByRole('link', { name: 'Crear Cliente' }).click();
  await page.getByRole('textbox', { name: 'Nombre*' }).click();
  await page.getByRole('textbox', { name: 'Nombre*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre*' }).fill('C');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre*' }).fill('Carlos');
  await page.getByRole('textbox', { name: 'Primer apellido*' }).click();
  await page.getByRole('textbox', { name: 'Nombre*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Primer apellido*' }).fill('R');
  await page.getByRole('textbox', { name: 'Primer apellido*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Primer apellido*' }).fill('Robles');
  await page.getByRole('textbox', { name: 'Segundo apellido' }).click();
  await page.getByRole('textbox', { name: 'Segundo apellido' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Segundo apellido' }).fill('M');
  await page.getByRole('textbox', { name: 'Segundo apellido' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Segundo apellido' }).fill('Montenegro');
  await page.getByRole('textbox', { name: 'Identificación*' }).click();
  await page.getByRole('textbox', { name: 'Identificación*' }).fill('402620223');
  await page.getByRole('textbox', { name: 'Correo electrónico*' }).click();
  await page.getByRole('textbox', { name: 'Correo electrónico*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Correo electrónico*' }).fill('C');
  await page.getByRole('textbox', { name: 'Correo electrónico*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Correo electrónico*' }).fill('Carloa');
  await page.getByRole('textbox', { name: 'Correo electrónico*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Correo electrónico*' }).fill('CarloaR');
  await page.getByRole('textbox', { name: 'Correo electrónico*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Correo electrónico*' }).fill('CarloaRobles@gmail.com');
  await page.locator('div:nth-child(7) > .fi-sc-component > .fi-fo-field').click();
  await page.locator('div:nth-child(7) > .fi-sc-component > .fi-fo-field').click();
  await page.getByRole('textbox', { name: 'Teléfono' }).fill('64582529');
  await page.getByRole('textbox', { name: 'Dirección' }).click();
  await page.getByRole('textbox', { name: 'Dirección' }).fill('29 metros sur ');
  await page.getByRole('textbox', { name: 'Notas' }).click();
  await page.getByRole('textbox', { name: 'Notas' }).fill('nada');
  await page.getByRole('button', { name: 'Seleccione una opción' }).click();
  await page.getByText('Distribuidora de Materiales S.A. -').click();
  await page.getByRole('option', { name: 'María Elena Solís Pérez -' }).click();
  await page.getByText('Nombre* Primer apellido*').click();
  await page.getByRole('button', { name: 'Crear' }).click();
  await page.getByRole('button', { name: 'Sí, crear' }).click();
  await page.getByRole('button', { name: 'Sí, crear' }).click();
  await page.locator('div').filter({ hasText: 'Confirmar creación ¿Deseas' }).nth(5).click();
  await page.getByRole('button', { name: 'Sí, crear' }).click();
  await page.getByRole('button', { name: 'Cerrar' }).click();
  await page.getByRole('textbox', { name: 'Identificación*' }).click();
  await page.getByRole('textbox', { name: 'Identificación*' }).fill('402620228');
  await page.getByRole('button', { name: 'Crear' }).click();
  await page.getByRole('button', { name: 'Sí, crear' }).click();
});