import { test, expect } from '@playwright/test';

test('Editar producto', async ({ page }) => {
  await page.goto('http://127.0.0.1:8000/admin');
  await page.getByRole('link', { name: 'Productos' }).click();
  await page.getByRole('link', { name: 'Editar' }).first().click();
  await page.getByRole('textbox', { name: 'Nombre*' }).click();
  await page.getByRole('textbox', { name: 'Nombre*' }).click();
  await page.getByRole('textbox', { name: 'Nombre*' }).fill('Laptop Dell Inspiron');
  await page.getByRole('textbox', { name: 'Nombre*' }).click();
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Nombre*' }).fill('Laptop hp Inspiron');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Nombre*' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Nombre*' }).fill('Laptop hp ');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await page.locator('.fi-modal-footer').click();
  await page.getByRole('button', { name: 'Sí, guardar' }).click();
  await page.getByRole('link', { name: 'Cancelar' }).click();
});